### ISSUE TITLE
本文中对于 EventHandler.ignoreCancelled 的解释疑似有误。

### ISSUE THREAD

**Issue by SNWCreations** [HamsterYDS/noticements-in-bukkit#1]
首先很感谢作者提供了如此好的一篇经验总结！
但是在阅读本文的过程中，我发现本文关于 EventHandler.ignoreCancelled 的讲解与 Bukkit API (参考的是 1.19.2 API 的中文版) 文档不符。
Bukkit API 文档原文为: 
> If ignoreCancelled is true and the event is cancelled, the method is not called. Otherwise, the method is always called.
译文: 如果 ignoreCancelled 为 true 并且事件被取消, 这个方法(注:应该指监听器方法)将不会被调用. 否则, 这个方法总是会调用。
并非 如果 ignoreCancelled 为 true 时，始终接受事件
与原文恰好相反。

请问是我的理解有问题吗？或实际情况与此不符？

期待您的回复！

**Comment by IceBear003** [comment]
一年前已经有人发现了这个bug，我也修改了正文，但是本文貌似有很多个副本，故没有一一修改，您看到的可能是旧版，感谢反馈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HamsterYDS/noticements-in-bukkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月14日(星期六) 晚上8:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HamsterYDS/noticements-in-bukkit] 本文中对于 EventHandler.ignoreCancelled 的解释疑似有误。 (Issue #1)





 
首先很感谢作者提供了如此好的一篇经验总结！
 但是在阅读本文的过程中，我发现本文关于 EventHandler.ignoreCancelled 的讲解与 Bukkit API (参考的是 1.19.2 API 的中文版) 文档不符。
 Bukkit API 文档原文为:
  
If ignoreCancelled is true and the event is cancelled, the method is not called. Otherwise, the method is always called.
 译文: 如果 ignoreCancelled 为 true 并且事件被取消, 这个方法(注:应该指监听器方法)将不会被调用. 否则, 这个方法总是会调用。
 并非 如果 ignoreCancelled 为 true 时，始终接受事件
 与原文恰好相反。
  
请问是我的理解有问题吗？或实际情况与此不符？
 
期待您的回复！
